- name: dummy
  ansible.builtin.debug:
    msg: hello component-shipping

- name: calling java function
  ansible.builtin.import_role:
    name: common
    tasks_from: java



#  mysql_password=$1
#
#  if [ -z "$mysql_password" ]; then
#  echo Input MySQL Root Password Missing
#  exit 1
#  else
#  echo ${mysql_password}
#  fi
#
#  component=shipping
#  schema_setup=mysql
#
#  func_java
