- name: dummy
  ansible.builtin.debug:
    msg: hello component-payment

- name: calling python function
  ansible.builtin.import_role:
    name: common
    tasks_from: python

- name: Import Prometheus
  ansible.builtin.import_role:
    name: prometheus
    tasks_from: node_exporter