- name: dummy
  ansible.builtin.debug:
    msg: hello component-frontend

- name: Install NJINX server
  ansible.builtin.yum:
    name: nginx
    state: installed

- name: Copy Config file
  ansible.builtin.copy:
    src: /templates/roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: Remove frontend directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: absent

- name: Create directory
  ansible.builtin.file:
    path: /usr/share/nginx/html
    state: directory

- name: Unarchive & Download frontend files
  ansible.builtin.unarchive:
    src: https://roboshop-artifacts.s3.amazonaws.com/frontend.zip
    dest: /usr/share/nginx/html
    remote_src: yes

- name: start NGINX server
  ansible.builtin.systemd:
    state: restarted
    name: nginx
    enabled: true